---
title: Cut&Tag Data Analysis -- Introduction
author: LiuYueR
date: '2021-07-15'
slug: Cut-Tag Analysis
categories:
  - Cut&Tag
  - Bioinformatics
tags:
  - Cut&Tag
  - Bioinformatics
lastmod: '2021-07-15T14:40:55+08:00'
keywords: []
description: ''
comment: no
toc: no
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---

## Cut&Tag 概述

所有发生在真核细胞核DNA上的动态过程都发生在染色质景观（chromatin landscape）之下。
染色质景观（chromatin landscape）由核小体及其修饰，转录因子和染色质相关复合物组成。
各种染色质特征标记是具有激活或者沉默转录调控元件和染色质结构域的位点，它们在不同的细胞类型和发育过程中发生变化。

传统上，全基因组染色质特征的定位是通过染色质免疫沉淀（ChIP）来进行的，其中染色质交联并溶解，蛋白质或者修饰的抗体用于结合DNA的免疫沉淀反应(Fig.1a)。
自从36年前第一次使用ChIP以来，ChIP的方式几乎没有改变，仍然充满了信号噪声问题。
另一种染色质分析策略是酶系原位，通过抗体或者融合蛋白靶向染色质蛋白或者感兴趣的修饰。然后对潜在的DNA进行标记或者切割，在过去的20年，一系列酶系原位方法被引用。 
Cleavage Under Targets & Tagmentation (CUT&Tag) 是一种使用蛋白-A-Tn5(pA-Tn5)的转座体融合蛋白的酶系原位的方法。
在CUT&Tag中，渗透化的细胞或细胞核与特定染色质蛋白的抗体一起孵育，然后与嵌合接头的pA-Tn5依次与抗体结合位点。
通过加入镁离子激活转座酶，导致接头与附近的DNA结合。然后对这些基因进行扩增，产生测序文库。基于酶系原位Tn5的方法，由于pA-Tn5栓系后对样本进行严格的清洗和接头整合效率高，因此具有较高的灵敏度。
与ChIP-seq相比，改进的信噪比意味着绘制染色质特征所需的测序量减少了一个数量级，允许在样本池（通常多达90个样本）通过barcode PCR文库在illumina NGS测序仪上进行双末端测序。



### Objectives

本教程是为了处理 **Cut&Tag** 数据而设计的。但是本教程也一般适用于任何染色质蛋白，包括转录因子、RNA聚合酶Ⅱ等等实验设计。

### 主要分析过程及软件

- 1.数据前期处理 Data Pre-processing (FastQC)
- 2.数据比对 (Bowtie2)
- 3.数据格式转化 Sam to bam, Bam to bed (Samtools, Bedtools)
- 4.Spike-in 矫正
- 5.Peak Calling (MACS2, SEACR)
- 6.数据可视化 Viualization (IGV)
- 7.差异Peaks分析 (deeptools, DESeq2)
- 8.Peaks注释 (GenomicFeatures, ChIPseeker)
- 9.Peaks关联基因的富集分析 (ClusterProfiler)
- 10.Motif分析 (MEME)



```{shell}
#R Package
- dplyr
- stringr
- ggplot2
- viridis
- GenomicFeatures
- GenomicRanges
- rtracklayer
- chromVAR
- DESeq2
- ggpubr
- corrplot
- ChIPseeker
- ClusterProfiler
- cowplot
	
#Software
- FastQC
- Bowtie2
- samtools
- bedtools
- Picard
- MACS2
- SEACR
- deepTools
- idr

```





